// Server-only AI logic behind the Source Idea "Generate for All Platforms"
// action. Each platform is generated by its own model call, so one failing
// platform never blocks the others.
import {
  SOURCE_IDEA_PLATFORM_LABEL,
  type SourceAnalysis,
  type SourceIdeaInput,
  type SourceIdeaPlatform,
  type SourcePlatformContent,
} from "@/lib/source-idea";

const MODEL = "google/gemini-3.6-flash";

export const SOURCE_IDEA_SYSTEM_PROMPT =
  "You are PostFlow AI, a platform-specific social media content strategist, SEO writer, copywriter, and hashtag researcher. " +
  "The user provides a source title. Analyse the title and generate separate optimized content for every requested social platform. " +
  "Never return the same caption, description, title, or hashtag list for every platform. " +
  "Adapt each result to the platform's audience, content style, search behaviour, character limits, and hashtag usage. " +
  "Generate relevant hashtag suggestions from the title and content context. " +
  "Never claim that hashtags are currently trending unless verified live trend data has been provided. Otherwise classify them as trending-style hashtag suggestions. " +
  "Do not invent facts, statistics, prices, product features, dates, results, or claims that are not present in the supplied input. " +
  "Avoid misleading clickbait, spam, banned hashtags, duplicate hashtags, and generic filler. " +
  "Return valid JSON only using the required schema. Do not return markdown or any text outside the JSON.";

const BANNED_HASHTAGS = new Set([
  "#follow4follow",
  "#followforfollow",
  "#like4like",
  "#likeforlike",
  "#f4f",
  "#l4l",
  "#followme",
  "#tagsforlikes",
  "#instagood2",
  "#sex",
  "#nude",
]);

const str = (v: unknown) => (typeof v === "string" ? v.trim() : "");

const rawList = (v: unknown): string[] =>
  Array.isArray(v)
    ? v.filter((x): x is string => typeof x === "string").map((x) => x.trim()).filter(Boolean)
    : typeof v === "string"
      ? v.split(/[\n,]+/).map((x) => x.trim()).filter(Boolean)
      : [];

/** De-duplicates, normalises and strips unsafe or spam-like hashtags. */
export function cleanHashtags(value: unknown, limit: number): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of rawList(value)) {
    for (const part of item.split(/\s+/)) {
      const tag = `#${part.replace(/^#+/, "").replace(/[^\p{L}\p{N}_]/gu, "")}`;
      if (tag.length < 3 || tag.length > 40) continue;
      const key = tag.toLowerCase();
      if (seen.has(key) || BANNED_HASHTAGS.has(key)) continue;
      seen.add(key);
      out.push(tag);
      if (out.length >= limit) return out;
    }
  }
  return out;
}

function cleanWords(value: unknown, limit: number): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of rawList(value)) {
    const word = item.replace(/^#/, "").trim();
    const key = word.toLowerCase();
    if (!word || seen.has(key) || word.length > 80) continue;
    seen.add(key);
    out.push(word);
    if (out.length >= limit) break;
  }
  return out;
}

/** Parses the model reply, tolerating code fences and stray prose. */
function parseJson(text: string | undefined): Record<string, unknown> | null {
  if (!text) return null;
  const cleaned = text.replace(/```(?:json)?/gi, "").trim();
  const candidates = [cleaned.match(/\{[\s\S]*\}/)?.[0], cleaned].filter(
    (v): v is string => typeof v === "string",
  );
  for (const candidate of candidates) {
    try {
      const parsed: unknown = JSON.parse(candidate);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return parsed as Record<string, unknown>;
      }
    } catch {
      // try the next candidate
    }
  }
  return null;
}

async function runModel(system: string, prompt: string, signal?: AbortSignal): Promise<string> {
  const key = process.env["LOVABLE_API_KEY"];
  if (!key) throw new Error("AI is not configured for this project yet.");
  const { createLovableAiGatewayProvider } = await import("@/lib/ai-gateway.server");
  const { streamText } = await import("ai");
  const gateway = createLovableAiGatewayProvider(key);
  try {
    // Streamed so long generations keep bytes flowing; only the final text is used.
    const options = signal ? { abortSignal: signal } : {};
    const result = streamText({ model: gateway(MODEL), system, prompt, ...options });
    return await result.text;
  } catch (error) {
    const err = error as { statusCode?: number; responseBody?: string; message?: string };
    const status = typeof err?.statusCode === "number" ? err.statusCode : undefined;
    const message = [err?.message, err?.responseBody, String(error)].filter(Boolean).join(" ");
    console.error("[SOURCE_IDEA_AI_ERROR]", { status, message: message.slice(0, 300) });
    if (status === 429 || message.includes("429") || /rate limit/i.test(message)) {
      throw new Error("AI is rate limited right now — try again shortly.");
    }
    if (
      status === 402 ||
      message.includes("402") ||
      /payment_required|not enough credits|credits/i.test(message)
    ) {
      throw new Error(
        "AI credits are exhausted for this workspace — add credits in Settings, then try again.",
      );
    }
    throw new Error("The AI writer could not be reached — try again.");
  }
}

const PLATFORM_BRIEF: Record<SourceIdeaPlatform, string> = {
  instagram:
    'Instagram post/Reel. Fields: hook (scroll-stopping first line, max 120 chars), caption (max 2200, readable, line breaks), emojiCaption (emoji-rich variant), cleanCaption (no emojis), shortDescription (max 200), cta (max 120), altText (max 1000), firstComment (extra hashtags/context), hashtags (12-20: broad + niche + topic + audience + location when relevant + one branded suggestion), trendingStyleHashtags (5-8 estimated, never claimed as live trends), keywords (8-12).',
  facebook:
    "Facebook post. Conversational and natural, fewer hashtags than Instagram. Fields: title (short headline, max 255), hook (max 150), caption (post text, max 5000), description (longer context), engagementQuestion, cta, firstComment, hashtags (3-6), keywords (6-10).",
  youtube:
    "YouTube long-form video. Fields: title (SEO friendly, max 100 chars, no misleading clickbait), hook (first description line), description (full description up to 4000 chars with a hook line, value summary and CTA), shortDescription (max 500), keywords (10-15 search keywords), tags (15-25 video tags, no # prefix), hashtags (max 5), pinnedComment, thumbnailText (3-5 words), cta (subscribe CTA).",
  youtube_shorts:
    'YouTube Shorts. Fields: title (max 80), hook (1 punchy line), shortDescription (max 300), description (short), cta, tags (8-15), hashtags (3-6, include #Shorts only when it fits), pinnedComment.',
  pinterest:
    "Pinterest pin, discovery and search first. Fields: title (max 100, keyword-first), description (max 500, keyword rich, natural), keywords (10-15 search keywords), hashtags (max 5), boardSuggestion (board name), altText (max 500), cta (destination-link CTA).",
  snapchat:
    "Snapchat. Brief and informal. Fields: caption (max 250), overlayText (3-6 words), cta (max 80), hashtags (max 3), emojiSuggestion (2-4 emojis).",
  linkedin:
    "LinkedIn. Professional and insight-led, no excessive hashtags. Fields: title (max 150), hook (professional hook, max 200), caption (insight-based, max 3000, short paragraphs), description (max 1200), cta (professional CTA), keywords (industry keywords, 6-10), hashtags (3-5).",
};

const CARD_SHAPE =
  '{"title":"","hook":"","caption":"","description":"","short_description":"","cta":"","hashtags":[],"trending_style_hashtags":[],"keywords":[],"tags":[],"alt_text":"","first_comment":"","pinned_comment":"","overlay_text":"","board_suggestion":"","thumbnail_text":"","emoji_caption":"","clean_caption":"","engagement_question":"","emoji_suggestion":""}';

function contextLines(input: SourceIdeaInput) {
  return [
    `Source title: ${input.title}`,
    `Language: ${input.language || "English"} — write everything in this language.`,
    input.tone && `Tone: ${input.tone}`,
    input.targetAudience && `Target audience: ${input.targetAudience}`,
    input.location && `Target location: ${input.location}`,
  ]
    .filter(Boolean)
    .join("\n");
}

function pick(c: Record<string, unknown>, ...keys: string[]) {
  for (const key of keys) {
    const value = str(c[key]);
    if (value) return value;
  }
  return "";
}

function normalize(platform: SourceIdeaPlatform, raw: unknown): SourcePlatformContent {
  const c = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  const hashtagLimit = platform === "snapchat" ? 3 : platform === "linkedin" ? 5 : platform === "instagram" ? 20 : 10;
  return {
    platform,
    title: pick(c, "title"),
    hook: pick(c, "hook"),
    caption: pick(c, "caption"),
    description: pick(c, "description"),
    shortDescription: pick(c, "short_description", "shortDescription"),
    cta: pick(c, "cta", "call_to_action", "callToAction"),
    hashtags: cleanHashtags(c["hashtags"], hashtagLimit),
    trendingStyleHashtags: cleanHashtags(
      c["trending_style_hashtags"] ?? c["trendingStyleHashtags"],
      8,
    ),
    keywords: cleanWords(c["keywords"], 20),
    tags: cleanWords(c["tags"], 30),
    altText: pick(c, "alt_text", "altText"),
    firstComment: pick(c, "first_comment", "firstComment"),
    pinnedComment: pick(c, "pinned_comment", "pinnedComment"),
    overlayText: pick(c, "overlay_text", "overlayText"),
    boardSuggestion: pick(c, "board_suggestion", "boardSuggestion"),
    thumbnailText: pick(c, "thumbnail_text", "thumbnailText"),
    emojiCaption: pick(c, "emoji_caption", "emojiCaption"),
    cleanCaption: pick(c, "clean_caption", "cleanCaption"),
    engagementQuestion: pick(c, "engagement_question", "engagementQuestion"),
    emojiSuggestion: pick(c, "emoji_suggestion", "emojiSuggestion"),
  };
}

function isEmpty(card: SourcePlatformContent) {
  return (
    !card.title &&
    !card.caption &&
    !card.description &&
    !card.shortDescription &&
    card.hashtags.length === 0
  );
}

/** Generates the content record for exactly one platform. */
export async function generatePlatformFromTitle(
  input: SourceIdeaInput,
  platform: SourceIdeaPlatform,
  signal?: AbortSignal,
): Promise<SourcePlatformContent> {
  const text = await runModel(
    SOURCE_IDEA_SYSTEM_PROMPT,
    [
      contextLines(input),
      "Step 1 — analyse the title only: main topic, content category, search intent, likely audience, best content angle, suitable tone and call-to-action. If the title is ambiguous, stay safe and general instead of inventing details.",
      `Step 2 — write content for ${SOURCE_IDEA_PLATFORM_LABEL[platform]} only, native to that platform:\n${PLATFORM_BRIEF[platform]}`,
      `Return JSON exactly shaped as {"content":${CARD_SHAPE}}. Use "" or [] for fields that do not apply. Return JSON only.`,
    ].join("\n\n"),
    signal,
  );
  const parsed = parseJson(text);
  const card = normalize(platform, parsed?.["content"] ?? parsed);
  if (isEmpty(card)) {
    throw new Error("The AI writer returned an unexpected response — try again.");
  }
  return card;
}

/** Analyses the source title on its own. */
export async function analyzeSourceTitle(
  input: SourceIdeaInput,
  signal?: AbortSignal,
): Promise<SourceAnalysis> {
  const text = await runModel(
    SOURCE_IDEA_SYSTEM_PROMPT,
    [
      contextLines(input),
      "Analyse this title only. Do not invent facts, prices, statistics, dates or product claims that the title does not contain.",
      'Return JSON exactly shaped as {"source_analysis":{"original_title":"","improved_title":"","topic":"","category":"","search_intent":"","target_audience":"","tone":"","keywords":[]}}. Return JSON only.',
    ].join("\n\n"),
    signal,
  );
  const parsed = parseJson(text);
  const a = (parsed?.["source_analysis"] ?? parsed ?? {}) as Record<string, unknown>;
  return {
    originalTitle: input.title,
    improvedTitle: pick(a, "improved_title", "improvedTitle"),
    topic: pick(a, "topic"),
    category: pick(a, "category"),
    searchIntent: pick(a, "search_intent", "searchIntent"),
    targetAudience: pick(a, "target_audience", "targetAudience") || input.targetAudience,
    tone: pick(a, "tone") || input.tone,
    keywords: cleanWords(a["keywords"], 15),
  };
}

export type SourceIdeaBatch = {
  analysis: SourceAnalysis;
  platforms: Partial<Record<SourceIdeaPlatform, SourcePlatformContent>>;
  warnings: string[];
};

/** Generates every requested platform; a single failure becomes a warning. */
export async function generateSourceIdeaBatch(
  input: SourceIdeaInput,
  platforms: SourceIdeaPlatform[],
  signal?: AbortSignal,
): Promise<SourceIdeaBatch> {
  const warnings: string[] = [];
  const analysis = await analyzeSourceTitle(input, signal).catch((error: unknown) => {
    warnings.push(
      `Title analysis failed: ${error instanceof Error ? error.message : "unknown error"}`,
    );
    return {
      originalTitle: input.title,
      improvedTitle: "",
      topic: input.title,
      category: "",
      searchIntent: "",
      targetAudience: input.targetAudience,
      tone: input.tone,
      keywords: [],
    } satisfies SourceAnalysis;
  });

  const results = await Promise.allSettled(
    platforms.map((platform) => generatePlatformFromTitle(input, platform, signal)),
  );

  const out: Partial<Record<SourceIdeaPlatform, SourcePlatformContent>> = {};
  results.forEach((result, index) => {
    const platform = platforms[index]!;
    if (result.status === "fulfilled") out[platform] = result.value;
    else {
      warnings.push(
        `${SOURCE_IDEA_PLATFORM_LABEL[platform]}: ${
          result.reason instanceof Error ? result.reason.message : "generation failed"
        }`,
      );
    }
  });

  return { analysis, platforms: out, warnings };
}
