/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountsRouteImport } from './routes/_authenticated/app.accounts'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppCreateRouteImport } from './routes/_authenticated/app.create'
import { Route as AuthenticatedAppGeneratorRouteImport } from './routes/_authenticated/app.generator'
import { Route as AuthenticatedAppMediaRouteImport } from './routes/_authenticated/app.media'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppPostsRouteImport } from './routes/_authenticated/app.posts'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as AuthenticatedAppAdminHealthRouteImport } from './routes/_authenticated/app.admin.health'
import { Route as AuthenticatedAppAdminJobsRouteImport } from './routes/_authenticated/app.admin.jobs'
import { Route as AuthenticatedAppAdminKeysRouteImport } from './routes/_authenticated/app.admin.keys'
import { Route as AuthenticatedAppAdminLogsRouteImport } from './routes/_authenticated/app.admin.logs'
import { Route as AuthenticatedAppAdminMusicRouteImport } from './routes/_authenticated/app.admin.music'
import { Route as AuthenticatedAppAdminPlatformsRouteImport } from './routes/_authenticated/app.admin.platforms'
import { Route as AuthenticatedAppAdminUsersRouteImport } from './routes/_authenticated/app.admin.users'
import { Route as ApiAiSourceIdeaGenerateRouteImport } from './routes/api/ai/source-idea/generate'
import { Route as ApiPublicPublishingRunRouteImport } from './routes/api/public/publishing/run'
import { Route as ApiPublicSupportJobStatusRouteImport } from './routes/api/public/support/job-status'
import { Route as ApiPublicOauthCallbackPlatformRouteImport } from './routes/api/public/oauth/callback.$platform'
import { Route as ApiPublicOauthConnectPlatformRouteImport } from './routes/api/public/oauth/connect.$platform'
import { Route as ApiPublicOauthFacebookScopesRouteImport } from './routes/api/public/oauth/facebook.scopes'
import { Route as ApiPublicOauthSnapchatPublicProfileCallbackRouteImport } from './routes/api/public/oauth/snapchat-public-profile.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountsRoute =
  AuthenticatedAppAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreateRoute = AuthenticatedAppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGeneratorRoute =
  AuthenticatedAppGeneratorRouteImport.update({
    id: '/generator',
    path: '/generator',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMediaRoute = AuthenticatedAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPostsRoute = AuthenticatedAppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminHealthRoute =
  AuthenticatedAppAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminJobsRoute =
  AuthenticatedAppAdminJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminKeysRoute =
  AuthenticatedAppAdminKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminLogsRoute =
  AuthenticatedAppAdminLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminMusicRoute =
  AuthenticatedAppAdminMusicRouteImport.update({
    id: '/music',
    path: '/music',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminPlatformsRoute =
  AuthenticatedAppAdminPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminUsersRoute =
  AuthenticatedAppAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const ApiAiSourceIdeaGenerateRoute = ApiAiSourceIdeaGenerateRouteImport.update({
  id: '/api/ai/source-idea/generate',
  path: '/api/ai/source-idea/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPublishingRunRoute = ApiPublicPublishingRunRouteImport.update({
  id: '/api/public/publishing/run',
  path: '/api/public/publishing/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportJobStatusRoute =
  ApiPublicSupportJobStatusRouteImport.update({
    id: '/api/public/support/job-status',
    path: '/api/public/support/job-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthCallbackPlatformRoute =
  ApiPublicOauthCallbackPlatformRouteImport.update({
    id: '/api/public/oauth/callback/$platform',
    path: '/api/public/oauth/callback/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthConnectPlatformRoute =
  ApiPublicOauthConnectPlatformRouteImport.update({
    id: '/api/public/oauth/connect/$platform',
    path: '/api/public/oauth/connect/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthFacebookScopesRoute =
  ApiPublicOauthFacebookScopesRouteImport.update({
    id: '/api/public/oauth/facebook/scopes',
    path: '/api/public/oauth/facebook/scopes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthSnapchatPublicProfileCallbackRoute =
  ApiPublicOauthSnapchatPublicProfileCallbackRouteImport.update({
    id: '/api/public/oauth/snapchat-public-profile/callback',
    path: '/api/public/oauth/snapchat-public-profile/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/accounts': typeof AuthenticatedAppAccountsRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/create': typeof AuthenticatedAppCreateRoute
  '/app/generator': typeof AuthenticatedAppGeneratorRoute
  '/app/media': typeof AuthenticatedAppMediaRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/posts': typeof AuthenticatedAppPostsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/health': typeof AuthenticatedAppAdminHealthRoute
  '/app/admin/jobs': typeof AuthenticatedAppAdminJobsRoute
  '/app/admin/keys': typeof AuthenticatedAppAdminKeysRoute
  '/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/app/admin/music': typeof AuthenticatedAppAdminMusicRoute
  '/app/admin/platforms': typeof AuthenticatedAppAdminPlatformsRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/api/ai/source-idea/generate': typeof ApiAiSourceIdeaGenerateRoute
  '/api/public/publishing/run': typeof ApiPublicPublishingRunRoute
  '/api/public/support/job-status': typeof ApiPublicSupportJobStatusRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/api/public/oauth/callback/$platform': typeof ApiPublicOauthCallbackPlatformRoute
  '/api/public/oauth/connect/$platform': typeof ApiPublicOauthConnectPlatformRoute
  '/api/public/oauth/facebook/scopes': typeof ApiPublicOauthFacebookScopesRoute
  '/api/public/oauth/snapchat-public-profile/callback': typeof ApiPublicOauthSnapchatPublicProfileCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/accounts': typeof AuthenticatedAppAccountsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/create': typeof AuthenticatedAppCreateRoute
  '/app/generator': typeof AuthenticatedAppGeneratorRoute
  '/app/media': typeof AuthenticatedAppMediaRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/posts': typeof AuthenticatedAppPostsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/health': typeof AuthenticatedAppAdminHealthRoute
  '/app/admin/jobs': typeof AuthenticatedAppAdminJobsRoute
  '/app/admin/keys': typeof AuthenticatedAppAdminKeysRoute
  '/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/app/admin/music': typeof AuthenticatedAppAdminMusicRoute
  '/app/admin/platforms': typeof AuthenticatedAppAdminPlatformsRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/api/ai/source-idea/generate': typeof ApiAiSourceIdeaGenerateRoute
  '/api/public/publishing/run': typeof ApiPublicPublishingRunRoute
  '/api/public/support/job-status': typeof ApiPublicSupportJobStatusRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/api/public/oauth/callback/$platform': typeof ApiPublicOauthCallbackPlatformRoute
  '/api/public/oauth/connect/$platform': typeof ApiPublicOauthConnectPlatformRoute
  '/api/public/oauth/facebook/scopes': typeof ApiPublicOauthFacebookScopesRoute
  '/api/public/oauth/snapchat-public-profile/callback': typeof ApiPublicOauthSnapchatPublicProfileCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/accounts': typeof AuthenticatedAppAccountsRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/create': typeof AuthenticatedAppCreateRoute
  '/_authenticated/app/generator': typeof AuthenticatedAppGeneratorRoute
  '/_authenticated/app/media': typeof AuthenticatedAppMediaRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/posts': typeof AuthenticatedAppPostsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/health': typeof AuthenticatedAppAdminHealthRoute
  '/_authenticated/app/admin/jobs': typeof AuthenticatedAppAdminJobsRoute
  '/_authenticated/app/admin/keys': typeof AuthenticatedAppAdminKeysRoute
  '/_authenticated/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/_authenticated/app/admin/music': typeof AuthenticatedAppAdminMusicRoute
  '/_authenticated/app/admin/platforms': typeof AuthenticatedAppAdminPlatformsRoute
  '/_authenticated/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/api/ai/source-idea/generate': typeof ApiAiSourceIdeaGenerateRoute
  '/api/public/publishing/run': typeof ApiPublicPublishingRunRoute
  '/api/public/support/job-status': typeof ApiPublicSupportJobStatusRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/api/public/oauth/callback/$platform': typeof ApiPublicOauthCallbackPlatformRoute
  '/api/public/oauth/connect/$platform': typeof ApiPublicOauthConnectPlatformRoute
  '/api/public/oauth/facebook/scopes': typeof ApiPublicOauthFacebookScopesRoute
  '/api/public/oauth/snapchat-public-profile/callback': typeof ApiPublicOauthSnapchatPublicProfileCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/register'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/accounts'
    | '/app/admin'
    | '/app/calendar'
    | '/app/create'
    | '/app/generator'
    | '/app/media'
    | '/app/notifications'
    | '/app/posts'
    | '/app/settings'
    | '/app/'
    | '/app/admin/health'
    | '/app/admin/jobs'
    | '/app/admin/keys'
    | '/app/admin/logs'
    | '/app/admin/music'
    | '/app/admin/platforms'
    | '/app/admin/users'
    | '/api/ai/source-idea/generate'
    | '/api/public/publishing/run'
    | '/api/public/support/job-status'
    | '/app/admin/'
    | '/api/public/oauth/callback/$platform'
    | '/api/public/oauth/connect/$platform'
    | '/api/public/oauth/facebook/scopes'
    | '/api/public/oauth/snapchat-public-profile/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/register'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/accounts'
    | '/app/calendar'
    | '/app/create'
    | '/app/generator'
    | '/app/media'
    | '/app/notifications'
    | '/app/posts'
    | '/app/settings'
    | '/app'
    | '/app/admin/health'
    | '/app/admin/jobs'
    | '/app/admin/keys'
    | '/app/admin/logs'
    | '/app/admin/music'
    | '/app/admin/platforms'
    | '/app/admin/users'
    | '/api/ai/source-idea/generate'
    | '/api/public/publishing/run'
    | '/api/public/support/job-status'
    | '/app/admin'
    | '/api/public/oauth/callback/$platform'
    | '/api/public/oauth/connect/$platform'
    | '/api/public/oauth/facebook/scopes'
    | '/api/public/oauth/snapchat-public-profile/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/register'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/auth/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/accounts'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/create'
    | '/_authenticated/app/generator'
    | '/_authenticated/app/media'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/posts'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/health'
    | '/_authenticated/app/admin/jobs'
    | '/_authenticated/app/admin/keys'
    | '/_authenticated/app/admin/logs'
    | '/_authenticated/app/admin/music'
    | '/_authenticated/app/admin/platforms'
    | '/_authenticated/app/admin/users'
    | '/api/ai/source-idea/generate'
    | '/api/public/publishing/run'
    | '/api/public/support/job-status'
    | '/_authenticated/app/admin/'
    | '/api/public/oauth/callback/$platform'
    | '/api/public/oauth/connect/$platform'
    | '/api/public/oauth/facebook/scopes'
    | '/api/public/oauth/snapchat-public-profile/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAiSourceIdeaGenerateRoute: typeof ApiAiSourceIdeaGenerateRoute
  ApiPublicPublishingRunRoute: typeof ApiPublicPublishingRunRoute
  ApiPublicSupportJobStatusRoute: typeof ApiPublicSupportJobStatusRoute
  ApiPublicOauthCallbackPlatformRoute: typeof ApiPublicOauthCallbackPlatformRoute
  ApiPublicOauthConnectPlatformRoute: typeof ApiPublicOauthConnectPlatformRoute
  ApiPublicOauthFacebookScopesRoute: typeof ApiPublicOauthFacebookScopesRoute
  ApiPublicOauthSnapchatPublicProfileCallbackRoute: typeof ApiPublicOauthSnapchatPublicProfileCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounts': {
      id: '/_authenticated/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AuthenticatedAppAccountsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/create': {
      id: '/_authenticated/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AuthenticatedAppCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/generator': {
      id: '/_authenticated/app/generator'
      path: '/generator'
      fullPath: '/app/generator'
      preLoaderRoute: typeof AuthenticatedAppGeneratorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/media': {
      id: '/_authenticated/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AuthenticatedAppMediaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/posts': {
      id: '/_authenticated/app/posts'
      path: '/posts'
      fullPath: '/app/posts'
      preLoaderRoute: typeof AuthenticatedAppPostsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/health': {
      id: '/_authenticated/app/admin/health'
      path: '/health'
      fullPath: '/app/admin/health'
      preLoaderRoute: typeof AuthenticatedAppAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/jobs': {
      id: '/_authenticated/app/admin/jobs'
      path: '/jobs'
      fullPath: '/app/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAppAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/keys': {
      id: '/_authenticated/app/admin/keys'
      path: '/keys'
      fullPath: '/app/admin/keys'
      preLoaderRoute: typeof AuthenticatedAppAdminKeysRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/logs': {
      id: '/_authenticated/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AuthenticatedAppAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/music': {
      id: '/_authenticated/app/admin/music'
      path: '/music'
      fullPath: '/app/admin/music'
      preLoaderRoute: typeof AuthenticatedAppAdminMusicRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/platforms': {
      id: '/_authenticated/app/admin/platforms'
      path: '/platforms'
      fullPath: '/app/admin/platforms'
      preLoaderRoute: typeof AuthenticatedAppAdminPlatformsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/users': {
      id: '/_authenticated/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AuthenticatedAppAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/api/ai/source-idea/generate': {
      id: '/api/ai/source-idea/generate'
      path: '/api/ai/source-idea/generate'
      fullPath: '/api/ai/source-idea/generate'
      preLoaderRoute: typeof ApiAiSourceIdeaGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publishing/run': {
      id: '/api/public/publishing/run'
      path: '/api/public/publishing/run'
      fullPath: '/api/public/publishing/run'
      preLoaderRoute: typeof ApiPublicPublishingRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support/job-status': {
      id: '/api/public/support/job-status'
      path: '/api/public/support/job-status'
      fullPath: '/api/public/support/job-status'
      preLoaderRoute: typeof ApiPublicSupportJobStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/callback/$platform': {
      id: '/api/public/oauth/callback/$platform'
      path: '/api/public/oauth/callback/$platform'
      fullPath: '/api/public/oauth/callback/$platform'
      preLoaderRoute: typeof ApiPublicOauthCallbackPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/connect/$platform': {
      id: '/api/public/oauth/connect/$platform'
      path: '/api/public/oauth/connect/$platform'
      fullPath: '/api/public/oauth/connect/$platform'
      preLoaderRoute: typeof ApiPublicOauthConnectPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/facebook/scopes': {
      id: '/api/public/oauth/facebook/scopes'
      path: '/api/public/oauth/facebook/scopes'
      fullPath: '/api/public/oauth/facebook/scopes'
      preLoaderRoute: typeof ApiPublicOauthFacebookScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/snapchat-public-profile/callback': {
      id: '/api/public/oauth/snapchat-public-profile/callback'
      path: '/api/public/oauth/snapchat-public-profile/callback'
      fullPath: '/api/public/oauth/snapchat-public-profile/callback'
      preLoaderRoute: typeof ApiPublicOauthSnapchatPublicProfileCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminHealthRoute: typeof AuthenticatedAppAdminHealthRoute
  AuthenticatedAppAdminJobsRoute: typeof AuthenticatedAppAdminJobsRoute
  AuthenticatedAppAdminKeysRoute: typeof AuthenticatedAppAdminKeysRoute
  AuthenticatedAppAdminLogsRoute: typeof AuthenticatedAppAdminLogsRoute
  AuthenticatedAppAdminMusicRoute: typeof AuthenticatedAppAdminMusicRoute
  AuthenticatedAppAdminPlatformsRoute: typeof AuthenticatedAppAdminPlatformsRoute
  AuthenticatedAppAdminUsersRoute: typeof AuthenticatedAppAdminUsersRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminHealthRoute: AuthenticatedAppAdminHealthRoute,
  AuthenticatedAppAdminJobsRoute: AuthenticatedAppAdminJobsRoute,
  AuthenticatedAppAdminKeysRoute: AuthenticatedAppAdminKeysRoute,
  AuthenticatedAppAdminLogsRoute: AuthenticatedAppAdminLogsRoute,
  AuthenticatedAppAdminMusicRoute: AuthenticatedAppAdminMusicRoute,
  AuthenticatedAppAdminPlatformsRoute: AuthenticatedAppAdminPlatformsRoute,
  AuthenticatedAppAdminUsersRoute: AuthenticatedAppAdminUsersRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountsRoute: typeof AuthenticatedAppAccountsRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCreateRoute: typeof AuthenticatedAppCreateRoute
  AuthenticatedAppGeneratorRoute: typeof AuthenticatedAppGeneratorRoute
  AuthenticatedAppMediaRoute: typeof AuthenticatedAppMediaRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPostsRoute: typeof AuthenticatedAppPostsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountsRoute: AuthenticatedAppAccountsRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCreateRoute: AuthenticatedAppCreateRoute,
  AuthenticatedAppGeneratorRoute: AuthenticatedAppGeneratorRoute,
  AuthenticatedAppMediaRoute: AuthenticatedAppMediaRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPostsRoute: AuthenticatedAppPostsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAiSourceIdeaGenerateRoute: ApiAiSourceIdeaGenerateRoute,
  ApiPublicPublishingRunRoute: ApiPublicPublishingRunRoute,
  ApiPublicSupportJobStatusRoute: ApiPublicSupportJobStatusRoute,
  ApiPublicOauthCallbackPlatformRoute: ApiPublicOauthCallbackPlatformRoute,
  ApiPublicOauthConnectPlatformRoute: ApiPublicOauthConnectPlatformRoute,
  ApiPublicOauthFacebookScopesRoute: ApiPublicOauthFacebookScopesRoute,
  ApiPublicOauthSnapchatPublicProfileCallbackRoute:
    ApiPublicOauthSnapchatPublicProfileCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
