// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function serviceRoleKeyType(value: string): "secret" | "service_role" | "invalid" {
  if (value.startsWith("sb_secret_")) return "secret";
  if (value.startsWith("sb_publishable_")) return "invalid";

  const [, payload] = value.split(".");
  if (!payload) return "invalid";
  try {
    const decoded = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as {
      role?: string;
    };
    return decoded.role === "service_role" ? "service_role" : "invalid";
  } catch {
    return "invalid";
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // The server admin client must never forward a user's JWT. Use only the
    // backend credential selected below.
    if (isNewSupabaseApiKey(supabaseKey)) {
      headers.delete("Authorization");
    } else {
      headers.set("Authorization", `Bearer ${supabaseKey}`);
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_SERVICE_ROLE_KEY = (process.env["SUPABASE_SERVICE_ROLE_KEY"] ?? "").trim();
  const SUPABASE_SECRET_KEY = (process.env["SUPABASE_SECRET_KEY"] ?? "").trim();
  const configuredKeys = [SUPABASE_SERVICE_ROLE_KEY, SUPABASE_SECRET_KEY].filter(Boolean);
  const SUPABASE_PRIVILEGED_KEY =
    configuredKeys.find((value) => serviceRoleKeyType(value) !== "invalid") ?? "";
  const privilegedKeyType = SUPABASE_PRIVILEGED_KEY
    ? serviceRoleKeyType(SUPABASE_PRIVILEGED_KEY)
    : "invalid";

  console.info("[SUPABASE_SERVER_CONFIG]", {
    supabase_url_configured: Boolean(SUPABASE_URL),
    supabase_service_role_key_configured: Boolean(SUPABASE_SERVICE_ROLE_KEY),
    supabase_secret_key_configured: Boolean(SUPABASE_SECRET_KEY),
    privileged_key_configured: Boolean(SUPABASE_PRIVILEGED_KEY),
    privileged_key_type: privilegedKeyType,
  });

  if (!SUPABASE_URL || !SUPABASE_PRIVILEGED_KEY || privilegedKeyType === "invalid") {
    const message = "Server Supabase admin credentials are not configured";
    console.error("[Supabase]", {
      message,
      supabase_url_configured: Boolean(SUPABASE_URL),
      supabase_service_role_key_configured: Boolean(SUPABASE_SERVICE_ROLE_KEY),
      supabase_secret_key_configured: Boolean(SUPABASE_SECRET_KEY),
      privileged_key_configured: Boolean(SUPABASE_PRIVILEGED_KEY),
    });
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PRIVILEGED_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PRIVILEGED_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
